### ISSUE TITLE
Revisit SORT and tracking code

### ISSUE THREAD

**Issue by nikk-nikaznan** [SainsburyWellcomeCentre/crabs-exploration#98]
- [x] the flow of the tracking
- [ ] better way of using SORT -- [SORT-pip](https://github.com/kadirnar/sort-pip) ?
   - Not maintained? Perhaps the script is better?
- [x] Shall we abandon [deep SORT](https://github.com/nwojke/deep_sort) ?
   - There are likely better newer "deep" tools.
   - YES we abandon this

**Comment by sfmig** [comment]
We have groundtruth 🥳 !

What format do we need it in?

@nikk-nikaznan suggests the one used in [MOTchallenge](https://motchallenge.net/instructions/) "basically a csv files with frame_no, object_id, bbox" -- seems easy 😬  enough to transform our json to this
